apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # namespace: nginx
  labels:
    app: nginx
spec:
  # nodeName: gke-kube1-default-pool-d3387ad4-5l32
  containers:
  - name: nginx
    image: nginx
    resources:
         limits:
           memory: "128Mi"
           cpu: "500m"
  nodeSelector:
    run: dev